[package]
name = "worldsim"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.35.0"
bevy_egui = "0.38.0"
bevy_rand = "0.12.1"
chrono = "0.4.42"
egui_dock = "0.18.0"
rand = "0.9.2"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
